services:
  wiki-md:
    image: ghcr.io/maitregeek/wiki-md:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATA_DIRECTORY=/app/data
      - LIST_ADMIN=
      - PORTFOLIO_LINK=
      - DONATION_LINK=
    volumes:
      - ./data:/app/data
    restart: unless-stopped
